version: '2'

services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/niming175/app-backend:latest
    env_file: 
      - app-backend.env
  cron:
    image: registry.cn-hangzhou.aliyuncs.com/niming175/app-backend:latest
    env_file:
      - app-backend.env
    command: ['cron', '-f']
  worker:
    image: registry.cn-hangzhou.aliyuncs.com/niming175/app-backend:latest
    env_file: 
      - app-backend.env
    command: ['/usr/bin/supervisord', '-n', '-c', '/etc/supervisor/supervisord.conf']
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/niming175/app-nginx:latest
    volumes_from:
      - backend
    depends_on:
      - backend
    ports:
      - "8888:80"

